name: Update METAR/TAF data

on:
  schedule:
    - cron: "*/5 * * * *"  # GitHub Actions minimum schedule is every 5 minutes (UTC)
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build status.json
        run: |
          python scripts/fetch_and_build.py

      - name: Commit & push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/status.json data/stations_icao.txt data/unmapped_airports.txt
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update METAR/TAF status data"
            git push
          fi
